site_name: Read@VRC.ONE
site_url: http://localhost:8000
theme:
  name: material
  features:
    - navigation.footer
copyright: Hosted by <a href="https://railgun.co">Railgun Network</a> / Coded with ❤️
extra:
  generator: false

nav:
  - Home: index.md
  - Books:
    - 《EJIN酱的How to Just ～从零开始的虚拟瑟瑟～》:
      - 前言: books/ejin-how-to-just/preface.md
      - 第一章: books/ejin-how-to-just/chapter-1.md
